import React, { useState } from 'react';
import { ChevronLeft, Download } from 'lucide-react';
import storage from '../storage';

const SummaryScreen = ({ profile, onBack }) => {
  const [timeRange, setTimeRange] = useState('7');
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(false);

  const generateSummary = () => {
    setLoading(true);
    
    const meds = storage.get(`meds-${profile.id}`) || [];
    const appointments = storage.get(`appointments-${profile.id}`) || [];
    const emergency = storage.get(`emergency-${profile.id}`) || {};

    const summaryText = `CARENEST HEALTH SUMMARY
Generated: ${new Date().toLocaleDateString()}

⚠️ DISCLAIMER: This summary is for organizational purposes only and does not constitute medical advice, diagnosis, or treatment. Please share this with your healthcare provider and discuss all concerns with them. If this is an emergency, contact local emergency services immediately.

═══════════════════════════════════════════════════
PROFILE INFORMATION
═══════════════════════════════════════════════════
Name: ${profile.name}
${profile.age ? `Age: ${profile.age} years old` : ''}
Summary Period: Last ${timeRange} days

═══════════════════════════════════════════════════
EMERGENCY INFORMATION
═══════════════════════════════════════════════════
${emergency.allergies?.length > 0 ? `Known Allergies: ${emergency.allergies.join(', ')}` : 'No allergies recorded'}
${emergency.contacts?.length > 0 ? `Emergency Contact: ${emergency.contacts[0].name} - ${emergency.contacts[0].phone}` : ''}
${emergency.hospital ? `Preferred Hospital: ${emergency.hospital}` : ''}

═══════════════════════════════════════════════════
MEDICATION LOG
═══════════════════════════════════════════════════
${meds.length > 0 ? meds.map(m => `${m.name}${m.time ? ` - Usual time: ${m.time}` : ''}`).join('\n') : 'No medications recorded'}

═══════════════════════════════════════════════════
APPOINTMENT HISTORY
═══════════════════════════════════════════════════
${appointments.length > 0 ? appointments.slice(0, 5).map(a => 
  `${a.date} - ${a.provider}\nReason: ${a.reason || 'Not specified'}\n${a.notes ? `Notes: ${a.notes}` : ''}`
).join('\n\n') : 'No appointments recorded'}

═══════════════════════════════════════════════════
QUESTIONS TO DISCUSS WITH HEALTHCARE PROVIDER
═══════════════════════════════════════════════════
1. What could be contributing to any patterns seen in my logs?
2. Are there specific triggers we should investigate further?
3. Should we track any additional information?
4. What warning signs should prompt immediate medical attention?
5. Are there any lifestyle modifications that might help?

═══════════════════════════════════════════════════

⚠️ REMINDER: This summary is for organizational purposes only. It does not provide medical advice, diagnosis, or treatment. Please consult with a qualified healthcare professional regarding all health concerns.

Generated by CareNest`;

    setSummary(summaryText);
    setLoading(false);
  };

  const copySummary = () => {
    navigator.clipboard.writeText(summary);
    alert('Summary copied to clipboard!');
  };

  return (
    <div className="min-h-screen p-4">
      <div className="max-w-3xl mx-auto">
        <div className="flex items-center gap-4 mb-6">
          <button onClick={onBack} className="p-2 hover:bg-white rounded-lg transition-colors">
            <ChevronLeft className="w-6 h-6 text-gray-700" />
          </button>
          <h1 className="text-2xl font-bold text-gray-900">Generate Summary - {profile.name}</h1>
        </div>

        {!summary ? (
          <div className="bg-white rounded-xl shadow-md p-6 space-y-6">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-3">Time Range</label>
              <div className="grid grid-cols-3 gap-3">
                <button
                  onClick={() => setTimeRange('7')}
                  className={`py-3 rounded-lg font-medium transition-colors ${
                    timeRange === '7' 
                      ? 'bg-indigo-600 text-white' 
                      : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                  }`}
                >
                  Last 7 Days
                </button>
                <button
                  onClick={() => setTimeRange('30')}
                  className={`py-3 rounded-lg font-medium transition-colors ${
                    timeRange === '30' 
                      ? 'bg-indigo-600 text-white' 
                      : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                  }`}
                >
                  Last 30 Days
                </button>
                <button
                  onClick={() => setTimeRange('90')}
                  className={`py-3 rounded-lg font-medium transition-colors ${
                    timeRange === '90' 
                      ? 'bg-indigo-600 text-white' 
                      : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                  }`}
                >
                  Last 90 Days
                </button>
              </div>
            </div>

            <button
              onClick={generateSummary}
              disabled={loading}
              className="w-full bg-gradient-to-r from-indigo-600 to-purple-600 text-white py-4 rounded-lg hover:from-indigo-700 hover:to-purple-700 transition-all font-medium text-lg disabled:opacity-50"
            >
              {loading ? 'Generating...' : 'Generate Doctor-Ready Summary'}
            </button>

            <div className="bg-amber-50 border border-amber-200 rounded-lg p-4">
              <p className="text-sm text-gray-800">
                This summary organizes your logged information for healthcare discussions. It does not diagnose or provide medical advice.
              </p>
            </div>
          </div>
        ) : (
          <div className="space-y-4">
            <div className="bg-white rounded-xl shadow-md p-6">
              <pre className="whitespace-pre-wrap text-sm text-gray-800 font-mono">{summary}</pre>
            </div>

            <div className="flex gap-3">
              <button
                onClick={copySummary}
                className="flex-1 bg-indigo-600 text-white py-3 rounded-lg hover:bg-indigo-700 transition-colors font-medium flex items-center justify-center gap-2"
              >
                <Download className="w-5 h-5" />
                Copy to Clipboard
              </button>
              <button
                onClick={() => setSummary(null)}
                className="px-6 bg-gray-200 text-gray-700 py-3 rounded-lg hover:bg-gray-300 transition-colors font-medium"
              >
                Generate New
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default SummaryScreen;
